#!/bin/sh
# Version: 4.54
# Run anything that is outside of sysinit
#

#  Test to see if we should halt on boot
#
if [ -f /usr/bin/fw_printenv ]
then
    /usr/bin/fw_printenv | grep -q haltboot
    if [ $? -eq 0 ]
    then
        echo " "
        echo "Synrad Boot: Halting"
        exit 0
    fi
fi

#  Check to see if we have a new version of U-Boot and
#  Kernel; if so, install U-Boot, and reboot into
#  the new Kernel.
#
if [ -f /home/u-boot.bin ]
then
    if [ -f /home/cuImage.yosemite.initramfs ]
    then
        echo " "
        echo " "
        echo "Initiating New Environmnet Upgrade"
        /bin/umount /filestore
        echo "Update: Erasing /dev/mtd3"
        /usr/sbin/flash_eraseall -q /dev/mtd3
        echo "Update: Installing New U-Boot"
        cat /home/u-boot.bin >> /dev/mtd3
	rm -f /home/u-boot.bin
        echo "Update: Setting Environment Variables"    
	mv /home/cuImage.yosemite.initramfs /cuImage.yosemite.initramfs 
        /usr/bin/fw_setenv flyer 
        /usr/bin/fw_setenv flyer 'run flashargs addip addtty;fsload 0x200000 cuImage.yosemite.initramfs; bootm 0x200000'
        /usr/bin/fw_setenv boot_state 
        /usr/bin/fw_setenv boot_state 1
        sync
        echo "Update: Reboot to new Kernel"    
        reboot
    fi
fi

# Run the script to test for flyermarker updates

/home/updateScripts/updatekernel
/home/updateScripts/updatemosaic

# NOTE: ONLY ONE OF THESE STATEMENTS BELOW CAN BE UNCOMMENTED

# UNCOMMENT BELOW FOR PRODUCTION SYSTEM
/sbin/hwclock --utc --hctosys
/home/mosaic&

# UNCOMMENT BELOW FOR DEVELOPMENT SYSTEM
#/home/flyertest&

# END NOTE

# webserver
/sbin/boa&
# UNCOMMENT BELOW FOR CUSTOMER REFLASH
#sleep 7
#/home/setled
#ash < /dev/ttygserial > /dev/ttygserial 2>&1
